import React, { useMemo, useState } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  ScrollView,
  KeyboardAvoidingView,
  Platform,
  StyleSheet,
  Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

import { saveTaxRecord } from '@/utils/storage';
import { formatCurrency } from '@/utils/formatter';
import { Colors } from '@/constants/calculatorstyles';

/* -----------------------------------------------------
   HELPERS
----------------------------------------------------- */
const parse = (v: string) => Number(v.replace(/,/g, '')) || 0;
const format = (v: string) =>
  v.replace(/[^0-9]/g, '')
    ? Number(v.replace(/[^0-9]/g, '')).toLocaleString()
    : '';

export default function CITCalculator() {
  const router = useRouter();

  const [step, setStep] = useState<1 | 2>(1);
  const [revenue, setRevenue] = useState('');
  const [expenses, setExpenses] = useState('');
  const [size, setSize] = useState<'small' | 'medium' | 'large'>('small');
  const [showBreakdown, setShowBreakdown] = useState(false);

  /* -----------------------------------------------------
     NIGERIAN CIT LOGIC (2026 UPDATED)
  ----------------------------------------------------- */
  const calc = useMemo(() => {
    const gross = parse(revenue);
    const deductions = parse(expenses);
    const taxableIncome = Math.max(gross - deductions, 0);

    // CIT Rates: Small (0%), Medium (20%), Large (30%)
    const citRate = size === 'large' ? 0.3 : size === 'medium' ? 0.2 : 0;

    // Development Levy (Replaces Education Tax in 2026): 4%
    // Small companies are exempt (0%)
    const devLevyRate = size === 'small' ? 0 : 0.04;

    const cit = taxableIncome * citRate;
    const devLevy = taxableIncome * devLevyRate;

    const totalTax = cit + devLevy;
    const netIncome = taxableIncome - totalTax;

    return {
      gross,
      deductions,
      taxableIncome,
      cit,
      devLevy,
      totalTax,
      netIncome,
      citRate,
      devLevyRate,
    };
  }, [revenue, expenses, size]);

  const handleProceed = async () => {
    if (!revenue) {
      Alert.alert('Missing Information', 'Enter company revenue');
      return;
    }

    // Save to local storage history
    try {
      const record = {
        id: Date.now().toString(),
        type: 'CIT',
        title: `${size.toUpperCase()} Company Tax`,
        userName: 'Corporate Entity',
        income: calc.taxableIncome.toString(),
        tax: calc.totalTax.toString(),
        net: calc.netIncome.toString(),
        date: new Date().toLocaleDateString(),
        time: new Date().toLocaleTimeString([], {
          hour: '2-digit',
          minute: '2-digit',
        }),
        year: '2026',
      };
      await saveTaxRecord(record);
    } catch (e) {
      console.error("Failed to save record", e);
    }

    setStep(2);
  };

  const resetCalculator = () => {
    setRevenue('');
    setExpenses('');
    setSize('small');      // default company size
    setShowBreakdown(false);
    setStep(1);
  };


  const downloadPDF = async () => {
    try {
      const html = `
        <html>
          <body style="font-family:Helvetica;padding:40px;color:#1e293b">
            <h2 style="text-align:center;color:${Colors.primary}">Corporate Tax Receipt</h2>
            <p style="text-align:center;">${size.toUpperCase()} COMPANY CATEGORY</p>
            <hr/>
            <div style="margin: 20px 0;">
              <p><strong>Gross Revenue:</strong> ${formatCurrency(calc.gross)}</p>
              <p><strong>Allowable Expenses:</strong> ${formatCurrency(calc.deductions)}</p>
              <p><strong>Taxable Profit:</strong> ${formatCurrency(calc.taxableIncome)}</p>
            </div>
            <div style="background-color: #f8fafc; padding: 20px; border-radius: 10px;">
              <p>CIT Rate (${calc.citRate * 100}%): ${formatCurrency(calc.cit)}</p>
              <p>Dev Levy (${calc.devLevyRate * 100}%): ${formatCurrency(calc.devLevy)}</p>
              <h3 style="color:${Colors.primary}; border-top: 1px solid #e2e8f0; padding-top: 10px;">
                Total Tax Payable: ${formatCurrency(calc.totalTax)}
              </h3>
              <h3>Net Profit After Tax: ${formatCurrency(calc.netIncome)}</h3>
            </div>
            <p style="text-align:center; font-size:10px; margin-top:50px; color:#94a3b8;">
              Generated by Taxlator Nigeria – 2026 Compliance Mode
            </p>
          </body>
        </html>
      `;

      const result = await Print.printToFileAsync({ html });

      if (result && result.uri) {
        await Sharing.shareAsync(result.uri, {
          mimeType: 'application/pdf',
          dialogTitle: 'Download Tax Receipt',
          UTI: 'com.adobe.pdf',
        });
      }
    } catch (error) {
      Alert.alert("Error", "Could not generate or share the PDF receipt.");
      console.error(error);
    }
  };

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: '#fff' }}>
      <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={{ flex: 1 }}>
        <ScrollView contentContainerStyle={{ padding: 20 }}>
          <TouchableOpacity onPress={() => router.back()}>
              <Text style={styles.backText}> <Ionicons name='chevron-back-outline' /> Back</Text>
            </TouchableOpacity>

          {step === 1 && (
            <View style={styles.card}>
              <Text style={styles.title}>Company Income Tax</Text>
              <Text style={styles.subtitle}>Select company size to apply 2026 Nigerian tax rates</Text>

              <Text style={styles.label}>Annual Revenue</Text>
              <TextInput
                value={revenue}
                onChangeText={(t) => setRevenue(format(t))}
                keyboardType="numeric"
                style={styles.input}
                placeholder="₦ 0"
              />

              <Text style={styles.label}>Company Classification</Text>
              {[
                { id: 'small', label: 'SMALL', rate: '0%', desc: 'Turnover < ₦50m' },
                { id: 'medium', label: 'MEDIUM', rate: '20%', desc: 'Turnover ₦50m - ₦100m' },
                { id: 'large', label: 'LARGE', rate: '30%', desc: 'Turnover > ₦100m' },
              ].map((item) => (
                <TouchableOpacity
                  key={item.id}
                  onPress={() => setSize(item.id as any)}
                  style={[styles.selector, size === item.id && styles.selectorActive]}
                >
                  <View style={styles.selectorRow}>
                    <Text style={styles.selectorLabel}>{item.label} COMPANY</Text>
                    <Text style={styles.selectorRate}>{item.rate} CIT</Text>
                  </View>
                  <Text style={styles.selectorDesc}>{item.desc}</Text>
                </TouchableOpacity>
              ))}

              <Text style={styles.label}>Operating Expenses</Text>
              <TextInput
                value={expenses}
                onChangeText={(t) => setExpenses(format(t))}
                keyboardType="numeric"
                style={styles.input}
                placeholder="₦ 0"
              />

              <TouchableOpacity style={styles.primary} onPress={handleProceed}>
                <Text style={styles.primaryText}>Calculate Tax</Text>
              </TouchableOpacity>
            </View>
          )}

          {step === 2 && (
            <View style={styles.resultCard}>
              <Text style={styles.resultTitle}>Total Tax Due ({size.toUpperCase()})</Text>
              <Text style={styles.resultValue}>{formatCurrency(calc.totalTax)}</Text>

              <View style={styles.row}>
                <ResultBox label="Taxable Profit" value={calc.taxableIncome} />
                <ResultBox label="Net Income" value={calc.netIncome} />
              </View>

              <TouchableOpacity style={styles.breakBtn} onPress={() => setShowBreakdown(!showBreakdown)}>
                <Text style={{fontWeight: '700'}}>View Tax Breakdown</Text>
                <Ionicons name={showBreakdown ? 'chevron-up' : 'chevron-down'} size={18} />
              </TouchableOpacity>

              {showBreakdown && (
                <View style={styles.breakdown}>
                  <Break label={`CIT Rate (${calc.citRate * 100}%)`} value={calc.cit} />
                  <Break label={`Dev. Levy (${calc.devLevyRate * 100}%)`} value={calc.devLevy} />
                  <View style={styles.divider} />
                  <Break label="Total Tax Payable" value={calc.totalTax} bold />
                </View>
              )}

            <TouchableOpacity style={styles.primary} onPress={resetCalculator}>
              <Text style={styles.primaryText}>New Calculation</Text>
            </TouchableOpacity>


              <TouchableOpacity style={[styles.primary, { backgroundColor: '#0ea5e9' }]} onPress={downloadPDF}>
                <Text style={styles.primaryText}>Download Receipt</Text>
              </TouchableOpacity>
            </View>
          )}
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

const ResultBox = ({ label, value }: any) => (
  <View style={styles.resultBox}>
    <Text style={styles.smallText}>{label}</Text>
    <Text style={styles.boxValue}>{formatCurrency(value)}</Text>
  </View>
);

const Break = ({ label, value, bold }: any) => (
  <View style={styles.breakRow}>
    <Text style={{color: '#475569'}}>{label}</Text>
    <Text style={{ fontWeight: bold ? '900' : '700', color: bold ? Colors.primary : '#1e293b' }}>
      {formatCurrency(value)}
    </Text>
  </View>
);

const styles = StyleSheet.create({
  back: { 
    color: Colors.primary, 
    marginBottom: 15, 
    fontWeight: '700' 
  },
  backText: { 
    color: Colors.card, 
    fontWeight: '700',
    backgroundColor: Colors.primary,
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: 5,
    width: 60,
    marginBottom: 20
  },
  card: { backgroundColor: '#fff', borderRadius: 20, padding: 20, elevation: 2, shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 10 },
  title: { fontSize: 22, fontWeight: '900', color: Colors.primary },
  subtitle: { fontSize: 13, color: '#64748b', marginBottom: 10 },
  label: { fontWeight: '800', marginTop: 20, color: '#1e293b', fontSize: 14 },
  input: { borderWidth: 1.5, borderColor: '#f1f5f9', padding: 14, borderRadius: 12, marginTop: 8, backgroundColor: '#f8fafc', fontSize: 16 },
  selector: { padding: 15, borderRadius: 12, borderWidth: 1.5, borderColor: '#f1f5f9', marginTop: 10, backgroundColor: '#fff' },
  selectorActive: { backgroundColor: '#f0f7ff', borderColor: Colors.primary },
  selectorRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  selectorLabel: { fontWeight: '800', fontSize: 14, color: '#1e293b' },
  selectorRate: { fontWeight: '900', color: Colors.primary, fontSize: 14 },
  selectorDesc: { fontSize: 11, color: '#64748b', marginTop: 2 },
  primary: { backgroundColor: Colors.primary, padding: 18, borderRadius: 14, marginTop: 15, alignItems: 'center' },
  primaryText: { color: '#fff', fontWeight: '800', fontSize: 16 },
  resultCard: { backgroundColor: '#fff', borderRadius: 24, padding: 24, borderWidth: 1, borderColor: '#f1f5f9' },
  resultTitle: { textAlign: 'center', color: '#64748b', fontWeight: '600', fontSize: 14 },
  resultValue: { fontSize: 36, fontWeight: '900', color: Colors.primary, textAlign: 'center', marginVertical: 10 },
  row: { flexDirection: 'row', gap: 12, marginTop: 10 },
  resultBox: { flex: 1, backgroundColor: '#f8fafc', padding: 16, borderRadius: 16, alignItems: 'center' },
  smallText: { fontSize: 11, color: '#64748b', fontWeight: '600' },
  boxValue: { fontWeight: '800', fontSize: 14, marginTop: 5, color: '#1e293b' },
  breakBtn: { marginTop: 25, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 5 },
  breakdown: { marginTop: 15, backgroundColor: '#f8fafc', padding: 20, borderRadius: 18 },
  breakRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  divider: { height: 1, backgroundColor: '#e2e8f0', marginVertical: 10 },
});