import React, { useMemo, useState } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  ScrollView,
  KeyboardAvoidingView,
  Platform,
  StyleSheet,
  Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

import { saveTaxRecord } from '@/utils/storage';
import { formatCurrency } from '@/utils/formatter';
import { Colors, styles as globalStyles } from '@/constants/calculatorstyles';

/* -----------------------------------------------------
   HELPERS
----------------------------------------------------- */
const parse = (v: string) => Number(v.replace(/,/g, '')) || 0;
const format = (v: string) =>
  v.replace(/[^0-9]/g, '')
    ? Number(v.replace(/[^0-9]/g, '')).toLocaleString()
    : '';

/* -----------------------------------------------------
   SCREEN
----------------------------------------------------- */
export default function CITCalculator() {
  const router = useRouter();

  const [step, setStep] = useState<1 | 2>(1);
  const [revenue, setRevenue] = useState('');
  const [expenses, setExpenses] = useState('');
  const [size, setSize] = useState<'small' | 'medium' | 'large'>('small');
  const [showBreakdown, setShowBreakdown] = useState(false);

  /* -----------------------------------------------------
     CORE NIGERIAN CIT LOGIC (2026 SAFE)
  ----------------------------------------------------- */
  const calc = useMemo(() => {
    const gross = parse(revenue);
    const deductions = parse(expenses);
    const taxableIncome = Math.max(gross - deductions, 0);

    const citRate =
      size === 'large' ? 0.3 : size === 'medium' ? 0.2 : 0;

    const educationTaxRate = size === 'small' ? 0 : 0.025;

    const cit = taxableIncome * citRate;
    const educationTax = taxableIncome * educationTaxRate;

    const totalTax = cit + educationTax;
    const netIncome = taxableIncome - totalTax;

    return {
      gross,
      deductions,
      taxableIncome,
      cit,
      educationTax,
      totalTax,
      netIncome,
      citRate,
      educationTaxRate,
    };
  }, [revenue, expenses, size]);

  /* -----------------------------------------------------
     SAVE + PROCEED
  ----------------------------------------------------- */
  const handleProceed = async () => {
    if (!revenue) {
      Alert.alert('Missing Information', 'Enter company revenue');
      return;
    }

    const record = {
      id: Date.now().toString(),
      type: 'CIT',
      title: 'Company Income Tax',
      userName: 'Corporate Entity',
      income: calc.taxableIncome.toString(),
      tax: calc.totalTax.toString(),
      net: calc.netIncome.toString(),
      date: new Date().toLocaleDateString(),
      time: new Date().toLocaleTimeString([], {
        hour: '2-digit',
        minute: '2-digit',
      }),
      year: '2026',
    };

    await saveTaxRecord(record);
    setStep(2);
  };

  /* -----------------------------------------------------
     PDF
  ----------------------------------------------------- */
  const downloadPDF = async () => {
    const html = `
      <html>
        <body style="font-family:Helvetica;padding:40px;color:#1e293b">
          <h2 style="text-align:center;color:${Colors.primary}">
            Company Income Tax Result
          </h2>

          <p><strong>Total Tax Due:</strong> ${formatCurrency(calc.totalTax)}</p>

          <hr/>

          <p>Gross Income: ${formatCurrency(calc.gross)}</p>
          <p>Total Deductions: ${formatCurrency(calc.deductions)}</p>
          <p>Taxable Income: ${formatCurrency(calc.taxableIncome)}</p>

          <p>CIT (${calc.citRate * 100}%): ${formatCurrency(calc.cit)}</p>
          <p>Education Tax (2.5%): ${formatCurrency(calc.educationTax)}</p>

          <h3>Total Tax: ${formatCurrency(calc.totalTax)}</h3>
          <h3>Net Income: ${formatCurrency(calc.netIncome)}</h3>

          <p style="margin-top:40px;font-size:10px;text-align:center">
            Generated by Taxlator Nigeria – 2026
          </p>
        </body>
      </html>
    `;

    const { uri } = await Print.printToFileAsync({ html });
    await Sharing.shareAsync(uri);
  };

  /* -----------------------------------------------------
     UI
  ----------------------------------------------------- */
  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: '#fff' }}>
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
        style={{ flex: 1 }}
      >
        <ScrollView contentContainerStyle={{ padding: 20 }}>
          <TouchableOpacity onPress={() => router.back()}>
            <Text style={styles.back}>
              <Ionicons name="chevron-back" /> Back
            </Text>
          </TouchableOpacity>

          {step === 1 && (
            <View style={styles.card}>
              <Text style={styles.title}>Company Income Tax</Text>
              <Text style={styles.subtitle}>
                Calculate company income tax based on Nigerian CIT rates
              </Text>

              <Text style={styles.label}>Revenue</Text>
              <TextInput
                value={revenue}
                onChangeText={(t) => setRevenue(format(t))}
                keyboardType="numeric"
                style={styles.input}
                placeholder="₦ 0"
              />

              <Text style={styles.label}>Company Size</Text>
              {(['small', 'medium', 'large'] as const).map((s) => (
                <TouchableOpacity
                  key={s}
                  onPress={() => setSize(s)}
                  style={[
                    styles.selector,
                    size === s && styles.selectorActive,
                  ]}
                >
                  <Text>{s.toUpperCase()} COMPANY</Text>
                </TouchableOpacity>
              ))}

              <Text style={styles.label}>Business Expenses</Text>
              <TextInput
                value={expenses}
                onChangeText={(t) => setExpenses(format(t))}
                keyboardType="numeric"
                style={styles.input}
                placeholder="₦ 0"
              />

              <TouchableOpacity
                style={styles.primary}
                onPress={handleProceed}
              >
                <Text style={styles.primaryText}>Proceed</Text>
              </TouchableOpacity>
            </View>
          )}

          {step === 2 && (
            <>
              <View style={styles.resultCard}>
                <Text style={styles.resultTitle}>
                  Company Income Tax Result
                </Text>
                <Text style={styles.resultValue}>
                  {formatCurrency(calc.totalTax)}
                </Text>
                <Text style={styles.smallText}>Total Tax Due</Text>

                <View style={styles.row}>
                  <ResultBox
                    label="Gross Income"
                    value={calc.gross}
                  />
                  <ResultBox
                    label="Net Income"
                    value={calc.netIncome}
                  />
                </View>

                <TouchableOpacity
                  style={styles.breakBtn}
                  onPress={() => setShowBreakdown(!showBreakdown)}
                >
                  <Text>View Tax Breakdown</Text>
                  <Ionicons
                    name={
                      showBreakdown ? 'chevron-up' : 'chevron-down'
                    }
                  />
                </TouchableOpacity>

                {showBreakdown && (
                  <View style={styles.breakdown}>
                    <Break label="Business Expenses" value={-calc.deductions} />
                    <Break label="Taxable Income" value={calc.taxableIncome} />
                    <Break label="CIT" value={calc.cit} />
                    <Break
                      label="Education Tax"
                      value={calc.educationTax}
                    />
                    <Break
                      label="Total Tax"
                      value={calc.totalTax}
                      bold
                    />
                  </View>
                )}
              </View>

              <TouchableOpacity
                style={styles.primary}
                onPress={() => setStep(1)}
              >
                <Text style={styles.primaryText}>
                  Calculate Another Tax
                </Text>
              </TouchableOpacity>

              <TouchableOpacity
                style={[styles.primary, { backgroundColor: Colors.accent }]}
                onPress={downloadPDF}
              >
                <Text style={styles.primaryText}>Download Receipt</Text>
              </TouchableOpacity>
            </>
          )}
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

/* -----------------------------------------------------
   SMALL COMPONENTS
----------------------------------------------------- */
const ResultBox = ({ label, value }: any) => (
  <View style={styles.resultBox}>
    <Text style={styles.smallText}>{label}</Text>
    <Text style={styles.boxValue}>{formatCurrency(value)}</Text>
  </View>
);

const Break = ({ label, value, bold }: any) => (
  <View style={styles.breakRow}>
    <Text>{label}</Text>
    <Text style={{ fontWeight: bold ? '800' : '600' }}>
      {formatCurrency(value)}
    </Text>
  </View>
);

/* -----------------------------------------------------
   STYLES
----------------------------------------------------- */
const styles = StyleSheet.create({
  back: {
    color: Colors.primary,
    marginBottom: 10,
    fontWeight: '700',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  title: { fontSize: 20, fontWeight: '800', color: Colors.primary },
  subtitle: { fontSize: 12, color: Colors.secondaryText, marginBottom: 20 },
  label: { fontWeight: '700', marginTop: 15 },
  input: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 12,
    borderRadius: 8,
    marginTop: 5,
  },
  selector: {
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    marginTop: 8,
  },
  selectorActive: {
    backgroundColor: '#eff6ff',
    borderColor: Colors.primary,
  },
  primary: {
    backgroundColor: Colors.primary,
    padding: 16,
    borderRadius: 10,
    marginTop: 20,
    alignItems: 'center',
  },
  primaryText: { color: '#fff', fontWeight: '800' },

  resultCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  resultTitle: { textAlign: 'center', color: '#64748b' },
  resultValue: {
    fontSize: 32,
    fontWeight: '900',
    color: Colors.primary,
    textAlign: 'center',
  },
  smallText: { fontSize: 11, color: '#64748b', textAlign: 'center' },
  row: { flexDirection: 'row', gap: 10, marginTop: 20 },
  resultBox: {
    flex: 1,
    backgroundColor: '#f8fafc',
    padding: 15,
    borderRadius: 10,
  },
  boxValue: { fontWeight: '800', marginTop: 4 },
  breakBtn: {
    marginTop: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  breakdown: {
    marginTop: 15,
    backgroundColor: '#f8fafc',
    padding: 15,
    borderRadius: 10,
  },
  breakRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
});
